### ISSUE TITLE
Responsive SVG's // use of viewBox

### ISSUE THREAD

**Issue by jwillem** [terezka/elm-plot#14]
Hey,

nice job 👍 

And I've got some improvements:
- Instead of defaulting to a explicit size of the plot, I would find it nice to include a `viewBox` in the Svg and to remove the height and width Attributes.
``` 
viewPlot : MetaConfig -> List (Svg.Svg msg) -> Svg.Svg msg
viewPlot { size, style } children =
    let
        ( width, height ) =
            size
    in
        Svg.svg
            [ Svg.Attributes.viewBox
                ("0 0 "
                    ++ (toString width)
                    ++ " "
                    ++ (toString height)
                )
            , Svg.Attributes.style (toStyle style)
            ]
            children
```

- The default behaviour would then be, that the svg is using the full size of the containing div. (when using the plot-fun. at least a container-div would be needed)
```
main =
     [  div [  style  
                    [ ("display", "flex")
                    ,  ("height", "300px")
                    ]
              ]
          [  plot
--          ...  
          ]
     ]
```
# or
- If the explicitness of a size would be needed, the SVG would get the provided measurements
  -- state of now.
- if no size would be set, default would be a `viewBox`-Attribute.
# or
- setting the `viewBox` always to e.g. "0 0 300 200" would be responisve (100%)
- setting it to `(toString width) ++ " " ++ (toString height) ++ "300 200"` would be the provided measurements

What do you think?

**Comment by terezka** [comment]
I'll try out the different approaches out and get back to you! Overall sounds like a good idea though!

**Comment by jwillem** [comment]
I've tested it in my current work project.. I need a graph which fills some 80% of the screen.
and especially when a scaling from ~600px to 1200px (or more on huge screens) it does not make any sense, because the texts are also scaled up/down. So multiple viewBoxes would be needed.. 
Another problem occurs when limiting the viewBox to a width of e.g. 1200px, this limits the scaling also to max. 1200px (scaling down works properly), so that I also would need to pass in a greater value than 1200. -- which would also eliminate the need for a scaling svg.

Maybe it would be still the easiest way to manually provide the measurements. (respectively in my usecase)

**Comment by jwillem** [comment]
🙌
