### ISSUE TITLE
Use css classnames instead of styles

### ISSUE THREAD

**Issue by jwillem** [terezka/elm-plot#15]
Additionally to inline-styles there should be the possibility to use css-classes instead.

**Comment by terezka** [comment]
Fixed! Search for "classes" in [the API docs](http://package.elm-lang.org/packages/terezka/elm-plot/2.1.0/Plot) for more info! (Pretty straight forward though)

**Comment by jwillem** [comment]
uuuuh, thanks! ☺️

**Comment by terezka** [comment]
Anytime, it's great with feedback!
