### ISSUE TITLE
Plotting a horizontal line

### ISSUE THREAD

**Issue by hillaryan** [terezka/elm-plot#25]
Lines of the form [(a,0),(b,0)] do not plot as expected. [(0,0)] also does not plot as expected.

This may be partly due to a div by zero here:
```
scaleValue : Scale -> Value -> Value
scaleValue { length, range, offset } v =
    (v * length / range) + offset.lower
```

A potential workaround is plotting a background-color vertical line.

**Comment by terezka** [comment]
Ah, right! Have a release coming up in a few days and will have it fix by then! Thanks for letting me know!

**Comment by terezka** [comment]
Hey you! I added a error message if you try to render something with a range or domain of zero, but also added a default range/domain of 0-1, so you don't run into it much. Will publish soon!
