### ISSUE TITLE
A curved line

### ISSUE THREAD

**Issue by amitaibu** [terezka/elm-plot#26]
While I don't have an immediate use case for this, I thought it would be great to have the possibility of showing a curved line plot. Something like:

![cdx](https://cloud.githubusercontent.com/assets/125707/21697747/885895ea-d39c-11e6-85a2-a274deff4617.jpg)

**Comment by terezka** [comment]
Hey you! Yeah, I totally feel ya, I need this myself. It's on the roadmap and depending on what is easiest, I will be working on either this or animations next!

**Comment by amitaibu** [comment]
Seems this is already in. Thank you!
