### ISSUE TITLE
onHover with overlapping plots

### ISSUE THREAD

**Issue by chancyk** [terezka/elm-plot#55]
With the new API you seem to be forced to overlap plots if you want to render multiple data series on the same axes, for instance:

![image](https://cloud.githubusercontent.com/assets/1731217/25444986/96588cc2-2a72-11e7-92b4-3736fefafa0f.png)

This works okay except the `onHover` of `PlotCustomizations` seems to only trigger on the top-most plot, which I'd think would not be a limitation of the DOM unless `stopPropagation` was being used, but seems to be what I'm experiencing.

**Comment by chancyk** [comment]
It seems like this actually is just an issue with how `mousemove` behaves with overlapping divs, as seen here: https://jsfiddle.net/s9ha5b5b/

`pointer-events: none` can be used to pass events through to a lower element, but there does not seem to be a simple way to trigger the event on all overlapping elements.

**Comment by terezka** [comment]
Hi! Thanks for writing! You can add two series in one plot though. Here's an [example](https://ellie-app.com/35SsHwDJSWsa1/0). Is there some condition causing this not to work?

P.S. Sorry for the late answer!

**Comment by chancyk** [comment]
I think that's going to work for me. I missed that I could just wrap my different series in a record to differentiate them in `toDataPoints`. ^ ^;

Thanks for your help! I'll close out this issue.
