### ISSUE TITLE
Unable to build Docs.elm

### ISSUE THREAD

**Issue by xarvh-at-stax** [terezka/elm-plot#58]
First of all, I really really like this library, thank you @terezka for all the time and effort and thought you put into it.

I have been struggling to understand how to use hints from the documentation, so I thought I would play around with the example code in https://terezka.github.io/elm-plot/ .

However, after cloning the repo, I couldn't find any way to build Docs.elm, there is no Readme nor Makefile, so I tried `elm-make Docs.elm` and a few more variations of that.

Eventually, it seems like the code uses an outdated version of elm-plot, because Docs.elm is trying to import a `PlotComposed` module that is not declared anywhere.

Thank you for your time and please let me know if I can help.

**Comment by skvale** [comment]
I think `docs/Docs.elm` is an artifact to be removed.
The updated one is located at `docs/src/Docs.elm`.
to build, run `elm-make docs/src/Docs.elm --output=docs/docs.js`

**Comment by terezka** [comment]
Thanks! 💛 Did @skvale's answer help? I'm working on the hint situation! I realize it's a little awkward at the moment! There should be an example use [here](https://github.com/terezka/elm-plot/blob/master/docs/src/PlotBars.elm).

**Comment by xarvh-at-stax** [comment]
@skvale thank you, that worked!

@terezka eventually I went through the library code to get a better idea of how to use the it.
We are going to use elm-plot in production, so I hope I'll be able to contribute some real-life example.
Looking forward to the hints update!
