### ISSUE TITLE
Need help with DateTime Axis?

### ISSUE THREAD

**Issue by anagrius** [terezka/elm-plot#60]
In our application we need a lot of timecharts. I was wondering if there are any plans on supporting them out of the box, or if you are interested in getting pull requests for tick positions and label formatting specifically for DateTime Axis?

**Comment by terezka** [comment]
It seems to be a common use, so that's a great idea! I'll add some helpers in the new version!

**Comment by anagrius** [comment]
Awesome. We have made our own and would love support out of the box. The biggest challenge was getting labels right. Meaning using meaningful dates (e.g. 1 days, 2 weeks, 3 months, 6 months) for arbitrary intervals. We ended up porting the logic from Highcharts:

https://github.com/highcharts/highcharts/blob/a270307bbc099909760b801bf877abb6a77f5581/js/parts/DateTimeAxis.js

Where they had done the ground work for us.

**Comment by stuartnelson3** [comment]
Definitely need this, as all the data I plot is for timeseries.

**Comment by anagrius** [comment]
Anyone done any work on this else I will start soon

**Comment by terezka** [comment]
Hi! I'm splitting the library into smaller chart libraries, so the work is being done here: https://github.com/terezka/lines

I haven't worked on data series specifically, so you can go ahead if you'd like :)

**Comment by anagrius** [comment]
That sounds like a great idea, as long as area and lines would have compatible options and data, since we switch between them based on user preference.

**Comment by terezka** [comment]
@anagrius You're right, I'll do that!

**Comment by terezka** [comment]
Done! Thanks for the reminder.
